# Generated by Django 6.0.5 on 2026-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_accessory_type_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
