# Generated by Django 6.0.5 on 2026-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_battery_product_camera_product_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_type',
            field=models.CharField(blank=True, choices=[('airpods', 'AirPods'), ('covers', 'Covers'), ('chargers', 'Chargers')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('accessory', 'Accessory')], default='phone', max_length=20),
        ),
    ]
