# Generated by Django 6.0.5 on 2026-05-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_percent_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
